spring.application.name=pilot

spring.datasource.url=jdbc:postgresql://localhost:5432/senai_zeiss
spring.datasource.username=postgres
spring.datasource.password=Thiago12345
spring.datasource.driverClassName=org.postgresql.Driver

server.port=8090